services:
  - type: web
    name: todo-app
    env: node
    buildCommand: npm ci && NODE_ENV=production node production-build.cjs
    startCommand: NODE_ENV=production node dist-production/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEON_DATABASE_URL
        sync: false