services:
  - type: web
    name: todo-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEON_DATABASE_URL
        sync: false # シークレット環境変数
      - key: PORT
        value: 10000