services:
  - type: web
    name: todo-app
    env: node
    buildCommand: npm ci && npm i vite --no-save && NODE_ENV=production node build-server-only.cjs
    startCommand: NODE_ENV=production node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEON_DATABASE_URL
        sync: false